[package]
name = "gnostr-relay"
version = "0.0.6"
description = "gnostr:a gnostr-relay"
authors = ["gnostt <admin@gnostr.org>", "Mike Dilger <mike@mikedilger.com>"]
license = "MIT"
repository = "https://github.com/gnostr-org/gnostr-relay"
edition = "2021"

[dependencies]
bytes = "1.6.0"
tui-term = { version = "0.2.0", features = ["unstable"] }
crossterm = "0.28"
ratatui = { version = "0.29.0", default-features = true }
vt100 = { version = "0.15.2", optional = true }
portable-pty = { version = "0.8.1" }


base64 = "0.22"
dashmap = "5.5"
env_logger = "0.10"
futures = "0.3"
hyper = { version = "0.14", features = [ "http1", "server", "runtime", "stream" ] }
hyper-tungstenite = "0.11"
lazy_static = "1.4"
log = "0.4"
pocket-types = { git = "https://github.com/mikedilger/pocket", branch = "master" }
pocket-db = { git = "https://github.com/mikedilger/pocket", branch = "master" }
parking_lot = "0.12"
rustls-pemfile = "1.0"
secp256k1 = { version = "0.28", features = [ "hashes", "global-context", "rand-std" ] }
serde = { version = "1.0", features = ["derive"] }
speedy = "0.8"
textnonce = "1"
tokio = { version = "1", features = [ "full" ] }
tokio-rustls = "0.24"
toml = "0.8"
url = "2.5"
gnostr-bins = "0.0.19"
serde_json = { version = "1.0.117", features = ["raw_value"] }
gnostr-types = "0.7.1-unstable"
async_command = "0.2.0"
async-process = "2.2.2"
async-executor = "1.11.0"
futures-lite = "2.3.0"

[dev-dependencies]
tempfile = "3"
