# See contrib/chorus.toml for a documented config file

data_directory = ".gnostr/relay"
ip_address = "127.0.0.1"
port = 6102
hostname = "localhost"
use_tls = false
certchain_pem_path = ".gnostr/relay/tls/fullchain.pem"
key_pem_path = ".gnostr/relay/tls/privkey.pem"
name = "gnostr"
description = "gnostr/relay"
open_relay = true
#pubkey for empty sha256
#e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
user_hex_keys = [
"a34b99f22c790c4e36b2b3c2c35a36db06226e41c692fc82b8b56ac1c540c5bd"
]
verify_events = true
allow_scraping = true
allow_scrape_if_limited_to = 100
allow_scrape_if_max_seconds = 7200
max_subscriptions = 128
serve_ephemeral = true
serve_relay_lists = true
server_log_level = "Trace"
library_log_level = "Trrace"
client_log_level = "Trace"
enable_ip_blocking = false
minimum_ban_seconds = 0
timeout_seconds = 0
